import Head from "next/head";
import Link from "next/link";
import Layout from "../components/Layout";
import BlogPost from "../components/BlogPost";

export async function getStaticProps() {
  const res = await fetch("http://localhost:3001/posts");
  const posts: any = await res.json();

  return { props: { posts } };
}

interface Post {
  id: number;
  title: string;
  content: string;
}

export default function Home({ posts }: any) {
  return (
    <>
      <Layout home>
        <Head>
          <title>Home Page</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="flex flex-col w-50 space-y-4">
          {posts.map((post: Post) => (
            <BlogPost
              key={post.id}
              id={post.id}
              title={post.title}
              content={post.content.slice(0, 100) + "..."}
            />
          ))}
        </div>
      </Layout>
    </>
  );
}
